spring:
  application:
    name: UserService-Microservices

  datasource:
    url: jdbc:mysql://localhost:3306/user_services
    username: root
    password: monu@2003
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import:
        - configserver:http://localhost:8085

server:
  port: 8080


